  version: "3"

  services:
    vitality_app:
      build:
        context: .
      ports:
          - "8000:8000"
      volumes:
          - ./vitality_app:/vitality_app
      command: >
        sh -c "python manage.py wait_for_db &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
      environment:
        - DB_HOST=db
        - DB_NAME=vitality_app
        - DB_USER=postgres
        - DB_PASS=superdupersecretpassword
      depends_on:
        - db

    db:
      image: postgres:10-alpine
      environment:
        - POSTGRES_DB=vitality_app
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=superdupersecretpassword
