# Generated by Django 2.2 on 2019-04-13 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('licenseNum', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('DBAName', models.CharField(max_length=100)),
                ('licenseType', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('processedDate', models.CharField(max_length=100)),
                ('startDate', models.CharField(max_length=100)),
                ('expireDate', models.CharField(max_length=100)),
                ('employeeNum', models.IntegerField(default=0)),
                ('companyType', models.CharField(max_length=100)),
                ('businessType', models.CharField(max_length=100)),
                ('propertyType', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Yelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenseNum', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('yelp_name', models.CharField(max_length=100)),
                ('yelp_id', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=1000)),
                ('is_claimed', models.CharField(max_length=100)),
                ('is_closed', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('review_count', models.CharField(max_length=10000)),
                ('transactions', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=1000)),
            ],
            options={
                'unique_together': {('licenseNum', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=100)),
                ('hasYelp', models.BooleanField(default=False)),
                ('hasGoogle', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Google',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenseNum', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('google_name', models.CharField(max_length=100)),
                ('google_id', models.CharField(max_length=100)),
                ('formatted_address', models.CharField(max_length=1000)),
                ('latitude', models.CharField(max_length=100)),
                ('longtitude', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('licenseNum', 'date')},
            },
        ),
    ]
