# Generated by Django 2.2 on 2019-04-14 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('license_num', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('dba_name', models.CharField(blank=True, max_length=100)),
                ('license_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('processed_date', models.CharField(blank=True, max_length=100)),
                ('start_date', models.CharField(blank=True, max_length=100)),
                ('expire_date', models.CharField(blank=True, max_length=100)),
                ('employee_num', models.IntegerField(blank=True, default=0)),
                ('company_type', models.CharField(blank=True, max_length=100)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('property_type', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('zipcode', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Google',
            fields=[
                ('google_name', models.CharField(max_length=100)),
                ('google_id', models.CharField(max_length=100)),
                ('formatted_address', models.CharField(max_length=1000)),
                ('latitude', models.CharField(max_length=100)),
                ('longtitude', models.CharField(max_length=100)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='business.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Yelp',
            fields=[
                ('yelp_name', models.CharField(max_length=100)),
                ('yelp_id', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=1000)),
                ('is_claimed', models.BooleanField(max_length=100)),
                ('is_closed', models.BooleanField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=5)),
                ('transactions', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=1000)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='business.Business')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business')),
            ],
            options={
                'unique_together': {('date', 'business')},
            },
        ),
        migrations.CreateModel(
            name='YelpHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('rating', models.FloatField(max_length=100)),
                ('review_count', models.IntegerField(default=0)),
                ('yelp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Yelp')),
            ],
            options={
                'unique_together': {('yelp', 'date')},
            },
        ),
        migrations.CreateModel(
            name='GoogleHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('rating', models.FloatField(max_length=100)),
                ('google', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Google')),
            ],
            options={
                'unique_together': {('google', 'date')},
            },
        ),
    ]
