# Generated by Django 2.1.7 on 2019-03-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('licenseNum', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('licenseType', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('processedDate', models.CharField(max_length=100)),
                ('startDate', models.CharField(max_length=100)),
                ('expireDate', models.CharField(max_length=100)),
                ('employeeNum', models.IntegerField(default=0)),
                ('companyType', models.CharField(max_length=100)),
                ('businessType', models.CharField(max_length=100)),
                ('propertyType', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField(default=0)),
            ],
        ),
    ]
