# Generated by Django 2.1.7 on 2019-03-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='id',
        ),
        migrations.AlterField(
            model_name='business',
            name='licenseNum',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
