# Generated by Django 2.1.7 on 2019-03-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenseNum', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('licenseType', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('processedDate', models.CharField(max_length=40)),
                ('startDate', models.CharField(max_length=40)),
                ('expireDate', models.CharField(max_length=40)),
                ('employeeNum', models.IntegerField(default=0)),
                ('companyType', models.CharField(max_length=20)),
                ('businessType', models.CharField(max_length=60)),
                ('propertyType', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=5)),
            ],
        ),
    ]
