# Generated by Django 2.1.7 on 2019-03-24 14:03
import os
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]
    # def generate_superuser(apps, schema_editor):
    #     from django.contrib.auth.models import User
    #     #DJANGO_SU_NAME = 'admin'
    #     DJANGO_SU_EMAIL = 'admin@admin.com'
    #     DJANGO_SU_PASSWORD = 'Password123'
    #
    #     superuser = User.objects.create_superuser(
    #         username=DJANGO_SU_NAME,
    #         email=DJANGO_SU_EMAIL,
    #         password=DJANGO_SU_PASSWORD)
    #     superuser.save()
    operations = [
        # migrations.RunPython(generate_superuser),
        migrations.CreateModel(

            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
